### PR TITLE
update some process to openms dev

### PR DESCRIPTION
**Pull request by ypriverol**
## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/quantms/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/quantms _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by jpfeuffer** [comment]
In theory that's ok but there is also the dev profile that switches to nightly containers.
So, I usually only update OpenMS versions for the parts where it's absolutely necessary for CI to succeed.

**Comment by ypriverol** [comment]
I think, If I'm honest, that all tools in Dev should be pointing to OpenMS Dev and only switch to release when Dev is merge into Master for release.

**Comment by ypriverol** [comment]
@jpfeuffer In the last commit https://github.com/bigbio/quantms/pull/289/commits/ec5b3aec47c0677627d8d7acb3bdb5e24ec57c15 I added the `id_transfer_threshold`. Can you check.

**Comment by jpfeuffer** [comment]
I think it should depend on requantification != none instead of targeted_only = false

**Comment by ypriverol** [comment]
you mean `transfer_ids != off`

**Comment by jpfeuffer** [comment]
Yes

**Pull request merged**
