### PR TITLE
Fixing quantms rescoring bugs

### PR DESCRIPTION
**Pull request by ypriverol**
This PR fixes the following Bug #458 

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/quantms/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/quantms _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Check for unexpected warnings in debug mode (`nextflow run . -profile debug,test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by jpfeuffer** [comment]
Could you please describe the bug in summary and how your changes fix that?

**Comment by ypriverol** [comment]
> Could you please describe the bug in summary and how your changes fix that?

For MSGF+ but also any other search engines, the rescoring algorithm was failing for psms without a main score. [#](https://github.com/bigbio/quantms/issues/458). 

In the current PR, @daichengxin https://github.com/bigbio/quantms-rescoring/pull/5/files#diff-d6a7c234404ec9682d47dca3803cc1755e81134d9f19b11b97264f46cf339296R254 is now handling better.

**Comment by jpfeuffer** [comment]
How can a PeptideHit not have a main score?
This is impossible in idXML.

**Comment by daichengxin** [comment]
Normal peptidehit:
```
		<PeptideIdentification score_type="SpecEValue" higher_score_better="false" significance_threshold="0.0" MZ="454.995086669921875" RT="631.48025999999993" spectrum_reference="controllerType=0 controllerNumber=1 scan=2402" >
			<PeptideHit score="5.606986999999999e-08" sequence=".(TMT6plex)AERALTM(Oxidation)YM(Oxidation)LK(TMT6plex)" charge="4" aa_before="K" aa_after="N" start="2366" end="2376" protein_refs="PH_2117" >
				<UserParam type="int" name="MS:1002049" value="58"/>
				<UserParam type="int" name="MS:1002050" value="133"/>
				<UserParam type="float" name="MS:1002052" value="5.606986999999999e-08"/>
				<UserParam type="float" name="MS:1002053" value="2.466499"/>
				<UserParam type="string" name="AssumedDissociationMethod" value="CID"/>
				<UserParam type="string" name="CTermIonCurrentRatio" value="0.5432841"/>
				<UserParam type="string" name="ExplainedIonCurrentRatio" value="0.64345765"/>
				<UserParam type="string" name="MS2IonCurrent" value="398487.38"/>
				<UserParam type="string" name="MeanErrorAll" value="264.05197"/>
				<UserParam type="string" name="MeanErrorTop7" value="312.92484"/>
				<UserParam type="string" name="MeanRelErrorAll" value="173.04474"/>
				<UserParam type="string" name="MeanRelErrorTop7" value="234.3867"/>
				<UserParam type="string" name="NTermIonCurrentRatio" value="0.100173555"/>
				<UserParam type="string" name="NumMatchedMainIons" value="9"/>
				<UserParam type="string" name="StdevErrorAll" value="277.724"/>
				<UserParam type="string" name="StdevErrorTop7" value="296.51938"/>
				<UserParam type="string" name="StdevRelErrorAll" value="341.92044"/>
				<UserParam type="string" name="StdevRelErrorTop7" value="361.8129"/>
				<UserParam type="float" name="calcMZ" value="455.007080078125"/>
				<UserParam type="int" name="pass_threshold" value="1"/>
				<UserParam type="int" name="start" value="2367"/>
				<UserParam type="int" name="end" value="2377"/>
				<UserParam type="string" name="target_decoy" value="decoy"/>
				<UserParam type="string" name="isotope_error" value="0"/>
				<UserParam type="string" name="protein_references" value="unique"/>
				<UserParam type="float" name="MSGF:ScoreRatio" value="0.43609022556391"/>
				<UserParam type="float" name="MSGF:Energy" value="75.0"/>
				<UserParam type="float" name="MSGF:lnEValue" value="-0.902799736258774"/>
				<UserParam type="float" name="MSGF:lnExplainedIonCurrentRatio" value="-0.44074366776915"/>
				<UserParam type="float" name="MSGF:lnNTermIonCurrentRatio" value="-2.299853277801329"/>
				<UserParam type="float" name="MSGF:lnCTermIonCurrentRatio" value="-0.609938842631449"/>
				<UserParam type="float" name="MSGF:lnMS2IonCurrent" value="12.895431107953099"/>
				<UserParam type="float" name="MSGF:MeanErrorTop7" value="312.924840000000017"/>
				<UserParam type="float" name="MSGF:sqMeanErrorTop7" value="9.79219554890256e04"/>
				<UserParam type="float" name="MSGF:StdevErrorTop7" value="296.519380000000012"/>
			</PeptideHit>
			<UserParam type="string" name="MS:1001115" value="2402"/>
		</PeptideIdentification>
```
A error example without search engines score features, and NumMatchedMainIons is 0. So we should remove it. I added a patch hander to skip them when extracting PSM. But I forget to synchronise the deletion of peptide ids.

```
		<PeptideHit score="5.607171999999999e-08" sequence=".(TMT6plex)WGFAK(TMT6plex)VQK(TMT6plex)" charge="3" aa_before="R" aa_after="I" start="335" end="342" protein_refs="PH_6493" >
				<UserParam type="int" name="MS:1002049" value="-6"/>
				<UserParam type="int" name="MS:1002050" value="17"/>
				<UserParam type="float" name="MS:1002052" value="5.607171999999999e-08"/>
				<UserParam type="float" name="MS:1002053" value="2.4330258"/>
				<UserParam type="string" name="AssumedDissociationMethod" value="HCD"/>
				<UserParam type="string" name="CTermIonCurrentRatio" value="0.0"/>
				<UserParam type="string" name="ExplainedIonCurrentRatio" value="0.0"/>
				<UserParam type="string" name="MS2IonCurrent" value="349679.66"/>
				<UserParam type="float" name="MeanErrorAll" value="0.0"/>
				<UserParam type="float" name="MeanErrorTop7" value="0.0"/>
				<UserParam type="float" name="MeanRelErrorAll" value="0.0"/>
				<UserParam type="float" name="MeanRelErrorTop7" value="0.0"/>
				<UserParam type="string" name="NTermIonCurrentRatio" value="0.0"/>
				<UserParam type="int" name="NumMatchedMainIons" value="0"/>
				<UserParam type="float" name="StdevErrorAll" value="0.0"/>
				<UserParam type="float" name="StdevErrorTop7" value="0.0"/>
				<UserParam type="float" name="StdevRelErrorAll" value="0.0"/>
				<UserParam type="float" name="StdevRelErrorTop7" value="0.0"/>
				<UserParam type="float" name="calcMZ" value="551.0147705078125"/>
				<UserParam type="int" name="pass_threshold" value="1"/>
				<UserParam type="int" name="start" value="336"/>
				<UserParam type="int" name="end" value="343"/>
				<UserParam type="string" name="target_decoy" value="decoy"/>
				<UserParam type="string" name="isotope_error" value="1"/>
				<UserParam type="string" name="protein_references" value="unique"/>
			</PeptideHit>
```

**Comment by jpfeuffer** [comment]
Aha! That makes sense!

**Review by daichengxin — APPROVED** [review]

**Pull request merged**
