### PR TITLE
Feature/open search ms fragger

### PR DESCRIPTION
**Pull request by tillenglert**
# Changes

This pull requests adds an open modification search feature to the QuantMS pipeline. The Open Modification search uses the MSFragger search engine to perform an peptide database search in a high range precursor mass window (e.g. -150 Da to 500 Da). The feature uses Crystal C, Philosopher PeptideProphet, PTMShepherd and a python script to create result histograms of each raw/mzML file used as input, Both tabular and graphical. Using this feature the modification landscape of samples can be analysed prior to the actual quantification to include possibly interesting modifications.

The Feature can be tested using the test_oms profile and an overview of the extended pipeline can be found at ./docs/images/QuantMS_OMS.png.

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [x] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/quantms/tree/master/.github/CONTRIBUTING.md)- [ ] If necessary, also make a PR on the nf-core/quantms _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [x] Make sure your code lints (`nf-core lint`).
- [x] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [x] Output Documentation in `docs/output.md` is updated.
- [x] `CHANGELOG.md` is updated.
- [x] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by jpfeuffer** [comment]
Thanks a lot for the contribution! One question: You say it can be used to explore the mod landscape before quantification.
What is missing to use the output files directly for quantification? In which format are the files?

Another hint: I think first indexing the database once for all input files would be MUCH faster.

**Comment by tillenglert** [comment]
> Thanks a lot for the contribution! One question: You say it can be used to explore the mod landscape before quantification. What is missing to use the output files directly for quantification? In which format are the files?


Hi sorry for the long delay on my answer.

The output of PTMShepherd is a tsv table with following structure:

Modification ⁄t Theoretical Mass Shift ⁄t Sample_Name_PSMs ⁄t Sample_Name_percent_PSMs
uridine phosphodiester ⁄t 306.025302 ⁄t 1070 ⁄t 20.9680
None ⁄t 0.0 ⁄t 739 ⁄t 14.4820
Unannotated mass-shift 249.0040 ⁄t 249.004 ⁄t 276 ⁄t 5.4080

I haven't had the time to look into it, but I suppose one could write a script fetching the topN modifications (excluding None and Unannotated mass-shifts) together with their mass and parse them to QuantMS as parameter.


> Another hint: I think first indexing the database once for all input files would be MUCH faster. Have you thought about that or even tried something in that direction?

I'm not quite sure what you mean by that, I haven't changed the handling of the database, compared to the other search engines, and use the prepared db for the MSFragger. Maybe you can elaborate more or write a dm?

**Comment by jpfeuffer** [comment]
Afaik MSFragger produces pepindex files for the fragment index per database and search settings.
This can be reused so the index does not need to be created for every mzml file but only once per database.

Not sure if there is a command line option to just create the index but we could use a dummy mzml file with only one spectrum or so, to do that and then use the pepindex file as input for the real searches with the mzmls.

**Comment by tillenglert** [comment]
> Afaik MSFragger produces pepindex files for the fragment index per database and search settings. This can be reused so the index does not need to be created for every mzml file but only once per database.
> 
> Not sure if there is a command line option to just create the index but we could use a dummy mzml file with only one spectrum or so, to do that and then use the pepindex file as input for the real searches with the mzmls.

https://assets.researchsquare.com/files/nprot-5701/v1/d8374e1e-b426-4c0c-bf5d-f501c59d0360.pdf?c=1631825097

"**Performance Considerations for Batch Processing** MSFragger allows multiple MS/MS input files to be processed in a batch. Passing multiple files to MSFragger at once allows MSFragger to reuse the fragment index for subsequent MS/MS run."

Unfortunately there is no command line option to mark files as batches, but of course one could sacrifice multithreading and collecting all files prior to MSFragger and merge them into one process. This could be faster dependent on the db file size and/or spectra file size. This could be tested on a large database and benchmarked. Unfortunately I am not able at the moment to perform large computational intensive testings, but certainly can look into it at some point!

**Pull request closed without merging**
