### PR TITLE
add name of each ID step

### PR DESCRIPTION
**Pull request by daichengxin**
## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
  - [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/quantms/tree/master/.github/CONTRIBUTING.md)
  - [ ] If necessary, also make a PR on the nf-core/quantms _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by jpfeuffer** [comment]
Very nice. Can we maybe call the output of msstats also after the input SDRF/experimental design?
E.g. pxd000123.mztab
pxd00123_msstats_in.csv

And in the msstats step
pxd000123_msstats_out.csv

**Comment by daichengxin** [comment]
You mean when run the msstats step, pxd000123_msstats_out.csv is displayed, right? Because the current msstats doesn't need the sdrf file, it doesn't seem to be able to `tag`. I probably didn't get what you meant. :cry:

**Comment by ypriverol** [comment]
I guess the name of the output should be based on the sdrf file name. I guess this is the suggestion from @jpfeuffer .

**Comment by jpfeuffer** [comment]
But if you name the output from ProteomicsLFQ etc based on the experimental design you can also parse that in msstats.

**Comment by jpfeuffer** [comment]
If the input to msstats is called pxd123_msstats_in.csv then you can just name the output pxd123_msstats_out.csv

**Comment by jpfeuffer** [comment]
Just use the input names.

**Review by ypriverol — APPROVED** [review]

**Pull request merged**
