### PR TITLE
DIA improvement

### PR DESCRIPTION
**Pull request by daichengxin**
## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
    - [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/quantms/tree/master/.github/CONTRIBUTING.md)
    - [ ] If necessary, also make a PR on the nf-core/quantms _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker` --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by jpfeuffer** [comment]
Why is it slower? 😂 Well.. i think it is still better this way

**Review by ypriverol — CHANGES_REQUESTED** [review]
@daichengxin in the dataset test for DIA that you are using, the authors filter the `Fragment m/z range` from 50 - 1500 and the minimum `precursor m/z range` was set to 350. I think we should set the parameters in the test to see if it speed up the process.

**Comment by jpfeuffer** [comment]
40 minutes, we are getting there. Why not reduce the m/z range even more? Just for CI.
On AWS full test data, we can use something that makes sense.

**Comment by ypriverol** [comment]
I will play a bit with these parameters to decrease this time.

**Pull request merged**
