### PR TITLE
enable mzTab for DIA-NN

### PR DESCRIPTION
**Pull request by WangHong007**

### CODE REVIEW

**Comment by WangHong007** [comment]
Hi Yasset! @ypriverol It seems `dia container` should be updated. This script makes additional use of the `Bio` Python package.

**Comment by jpfeuffer** [comment]
What do you need from the Bio package? Can we do without?

Is there an example output for the mzTab that is created?

**Comment by WangHong007** [comment]
An example is here: [`quantms/out.mztab`](https://github.com/WangHong007/Data-Folder/blob/1dd437d7f47158c7bd0729cad8af8ae07fe434cc/quantms/out.mztab)
We use `Bio` package to calculate `protein coverage` and `Calculate.Precursor.Mz`, and we can set these to "null" for now.

**Comment by ypriverol** [comment]
@WangHong007 Protein groups errors: 

I have validated the following mzTab [out.mzTab](https://github.com/WangHong007/Data-Folder/blob/1dd437d7f47158c7bd0729cad8af8ae07fe434cc/quantms/out.mztab). I found the following error: 

```
[Error-1019] line 103: Column "protein_coverage" value "0.024;0.025" is not a valid Double value.
[Error-1019] line 171: Column "protein_coverage" value "0.032;0.038" is not a valid Double value.
[Error-1019] line 285: Column "protein_coverage" value "0.029;0.035;0.036" is not a valid Double value.
[Error-1019] line 515: Column "protein_coverage" value "0.257;0.257" is not a valid Double value.
[Error-1019] line 884: Column "protein_coverage" value "0.069;0.069" is not a valid Double value.
[Error-1019] line 919: Column "protein_coverage" value "0.047;0.047" is not a valid Double value.
[Error-1019] line 1320: Column "protein_coverage" value "0.027;0.032" is not a valid Double value.
[Error-1019] line 1375: Column "protein_coverage" value "0.052;0.052" is not a valid Double value.
```

This is mainly because protein groups are added by your script as 

```
PRT	P02919;P02919-2	Penicillin-binding protein 1B	1.26E+06	1.12E+06	1.24E+06	1.34E+06	1.15E+06	1.31E+06	ref_ecoli_k12_ups1_combined	null	null	null	null	null	null	null	0.024;0.025	P02919;P02919-2	0.000861326	null	1178004.286	null	null	1296266.875	null	null	single_protein
```

**This is not valid in the mzTab.** 

The OpenMS approach @timosachsenberg is to write for each protein group the following: 

1- indistinguishable_protein_group: `PRT	MAPHEAD100010850	null	null	null	mgm-proteins-decoy	null	null	5.524861878453039e-03	MAPHEAD100010850,MAPHEAD100677610	null	0.061311661311661	2.0	2.0	null	null	null	null	null	indistinguishable_protein_group` In this case select the first protein of the protein group for your protein `P02919`. 
2- Write the two proteins as protein_details. @timosachsenberg has selected to write each member of the group as a single entry with the optional column `protein_details`. For example: `PRT	MAPHEAD100010850	null	null	null	mgm-proteins-decoy	null	null	2.173913043478261e-03	null	null	0.072727272727273	null	null	null	null	null	2	0	protein_details`

With that, you will be able to write of each member of the group the sequence coverage as double and will be a valid protein. 

Here is an example: 

[PXD020692-Sample-12.sdrf_openms_design_openms.mzTab.zip](https://github.com/bigbio/quantms/files/9197771/PXD020692-Sample-12.sdrf_openms_design_openms.mzTab.zip)

**Comment by WangHong007** [comment]
@ypriverol Got it. I will write the two or more proteins as `protein_details`.

**Comment by WangHong007** [comment]
Hi ! @vdemichev @ypriverol 
How can we identify protein type(`opt_global_result_type` in mzTab) according to Dia-NN main report and matrixs? 

For now, I'm classifying by the number of protein ID separated by semicolons in the columns `Protein.Group` and `Protein.Ids` in aforementioned result files.
e.g.
`Protein.Group="P09152;P19319", Protein.Ids="P09152;P19319"` --> `protein_details`
`Protein.Group="P09152", Protein.Ids="P09152;P19319"` --> `indistinguishable_protein_group`
`Protein.Group="P09152", Protein.Ids="P09152"` --> `single_protein`

**Comment by WangHong007** [comment]
jmztab online: [mztabvalidator](https://apps.lifs.isas.de/mztabvalidator/)
An example is here: [diatest_out.mztab](https://github.com/WangHong007/Data-Folder/blob/0cb05735e09d5bf34ca8bc28a8c9d2216db53b20/quantms/diatest.sdrf_openms_design_out.mztab)

**Comment by ypriverol** [comment]
> Hi ! @vdemichev @ypriverol How can we identify protein type(`opt_global_result_type` in mzTab) according to Dia-NN main report and matrixs?
> 

> For now, I'm classifying by the number of protein ID separated by semicolons in the columns `Protein.Group` and `Protein.Ids` in aforementioned result files. e.g. `Protein.Group="P09152;P19319", Protein.Ids="P09152;P19319"` --> `protein_details` `Protein.Group="P09152", Protein.Ids="P09152;P19319"` --> `indistinguishable_protein_group` `Protein.Group="P09152", Protein.Ids="P09152"` --> `single_protein`


@WangHong007 I don't understand the question here.

**Comment by WangHong007** [comment]
> 
> 1- indistinguishable_protein_group: `PRT MAPHEAD100010850 null null null mgm-proteins-decoy null null 5.524861878453039e-03 MAPHEAD100010850,MAPHEAD100677610 null 0.061311661311661 2.0 2.0 null null null null null indistinguishable_protein_group` In this case select the first protein of the protein group for your protein `P02919`. 
2- Write the two proteins as protein_details. @timosachsenberg has selected to write each member of the group as a single entry with the optional column `protein_details`. For example: `PRT MAPHEAD100010850 null null null mgm-proteins-decoy null null 2.173913043478261e-03 null null 0.072727272727273 null null null null null 2 0 protein_details`
> 

The question is to determine the type of protein identification result in the protein subtable. How to get three result types(`single_protein`, `protein_details`, `Indistinguishable_protein_group`) from DIA-NN main report and matrix file. 

For now, I use the number of values(one-to-one, many-to-many or one-to-many) corresponding to the two columns  `Protein.Group` and `Protein.Ids` in DIA-NN result files.

> e.g. 
`Protein.Group="P09152", Protein.Ids="P09152"` --> `single_protein`
`Protein.Group="P09152;P19319", Protein.Ids="P09152;P19319"` --> `protein_details` 
`Protein.Group="P09152", Protein.Ids="P09152;P19319"` --> `indistinguishable_protein_group`

**Comment by ypriverol** [comment]
@WangHong007, here how those cases should be annotated: 

- `Protein.Group="P09152", Protein.Ids="P09152" --> single_protein` This is single protein and not protein_details needs to be annotated. 
- Protein.Group="P09152;P19319", Protein.Ids="P09152;P19319" should be annotated as: 
    - Select the first protein accession `P09152` as the ancore of the group and the others are `ambiquity_memebers`.
    - The `opt_global_result_type can be annotated as `indistinguishable_protein_group`. 
    - Each protein of the group P09152; P19319 should be also annotated as protein_details where you add the coverage, score, etc. for each protein. 
- Protein.Group="P09152", Protein.Ids="P09152;P19319" should be annotated as: 
    - `P09152` as the ancore of the group and the others are `ambiquity_members`.
    - The `opt_global_result_type can be annotated as `indistinguishable_protein_group`. 
    - Each protein of the group P09152; P19319 should be also annotated as protein_details where you add the coverage, score, etc. for each protein.

**Comment by ypriverol** [comment]
@WangHong007 The problem that you have there is that the dependency `pyopenms` is not installed when you run as script using docker.

**Review by ypriverol — APPROVED** [review]

**Review by ypriverol — APPROVED** [review]

**Pull request merged**
