### PR TITLE
dynamic version

### PR DESCRIPTION
**Pull request by WangHong007**

### CODE REVIEW

**Comment by WangHong007** [comment]
It seems that `pyopenms`, `openms` and `openms-thirdparty` conflict when creating environments using conda.

**Review by jpfeuffer — COMMENTED** [review]
Looks good in general. Did you check the output?
I'm surprised that you can check packages with pip when they are installed with Conda.

**Comment by WangHong007** [comment]
@jpfeuffer Hi Julianus! 

When I run with conda use `"import pyopenms; print(pyopenms.__version__)"`, I got the following version information:
```
"NFCORE_QUANTMS:QUANTMS:FILE_PREPARATION:MZMLSTATISTICS":
    pyopenms: Warning: OPENMS_DATA_PATH environment variable already exists. pyOpenMS will use it (/home/qinchunyuan/proteomicsDIA/quantms-newPR/work/conda/env-b594964cb2f9d0131205be432178f63f/share/OpenMS/) to locate data in the OpenMS share folder (e.g., the unimod database), instead of the default (/home/qinchunyuan/proteomicsDIA/quantms-newPR/work/conda/env-b594964cb2f9d0131205be432178f63f/lib/python3.10/site-packages/pyopenms/share/OpenMS).
2.8.0
```
To achieve the dynamic version I used `pip show package` and the output looks fine, here [collated_versions.yml](https://github.com/WangHong007/Data-Folder/blob/9a67e8ad7bc79cc0146b585b26dc3c992e462265/quantms/collated_versions.yml). The error in conda CI is very strange.

**Comment by jpfeuffer** [comment]
That warning should not happen on fresh installs and we could add a regex to parse for the version after the warning. But if `pip show` works for both Conda and Container, I am fine with it.

**Comment by jpfeuffer** [comment]
The Conda error is just a race condition of Conda/mamba trying to install multiple environments. We should try the new micromamba support in another PR.

**Comment by ypriverol** [comment]
should we force this merge?

**Pull request merged**
