### PR TITLE
first commit msstatistics csv -> parquet [DO NOT MERGE]

### PR DESCRIPTION
**Pull request by ypriverol**
## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/quantms/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/quantms _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nf-test test main.nf.test -profile test,docker`).
- [ ] Check for unexpected warnings in debug mode (`nextflow run . -profile debug,test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by ypriverol** [comment]
Pending of https://github.com/bigbio/quantms-utils/pulls and also future release of the package.

**Comment by jpfeuffer** [comment]
Cool. Looks like we are down from 3.5 to 1.3 GB for the DIA test

**Comment by ypriverol** [comment]
> Cool. Looks like we are down from 3.5 to 1.3 GB for the DIA test

We still have the issue with mamba and micromamba tests.

**Comment by jpfeuffer** [comment]
I think it's ok if you skip them for now. I will check if there is a solution by now. It was always a flaky test due to the multiple processes that try to create/change cobra environments.

Or does it fail because sth else? No, right?

**Pull request merged**
