### PR TITLE
version fix

### PR DESCRIPTION
**Pull request by daichengxin**
## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
    - [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/quantms/tree/master/.github/CONTRIBUTING.md)
    - [ ] If necessary, also make a PR on the nf-core/quantms _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by jpfeuffer** [comment]
The version has to be 11 otherwise markdown linting fails

**Comment by daichengxin** [comment]
> The version has to be 11 otherwise markdown linting fails

ok. I am removing functions.nf

**Comment by jpfeuffer** [comment]
There is probably a way to ignore tests in the nf-core linting. We should ignore the markdown linting.yml until this is fixed by  them.

**Review by jpfeuffer — APPROVED** [review]

**Comment by daichengxin** [comment]
The code to determine whether it is tmt or lfq needs to be changed. Honestly, it's a bit difficult. Because the value in the DataflowStream object cannot be extracted

**Comment by jpfeuffer** [comment]
How do you mean? Can you post links to the code?

**Review by ypriverol — APPROVED** [review]

**Comment by jpfeuffer** [comment]
I give up

**Comment by daichengxin** [comment]
> I give up

I'll try it too. A little difficult. :sob:

**Comment by jpfeuffer** [comment]
@daichengxin Can you fix pMultiQC such that it reads ISO or LFQ from the mztab if that parameter is not given? Should be one of the entries in the mztab metadata.

**Comment by jpfeuffer** [comment]
What do you think? Ready to merge?

**Pull request merged**
